### ISSUE TITLE
Add "type constructors"?

### ISSUE THREAD

**Issue by stoft** [sporto/elm-tutorial#1]
You may want to confirm this with another source (I'm new to typed languages), but I think e.g. `Array` in e.g. `indexOf : String -> Array String -> Int` is called a _type constructor_, might be worth adding to the book?

Ref: https://wiki.haskell.org/Constructor

**Comment by sporto** [comment]
@stoft I'm don't really know, I'm new to ML languages too, will investigate

**Comment by gareth-rowlands-akqa** [comment]
In Haskell at least, `Array` is indeed called a _type constructor_. Applying `Array` to a concrete type such as `String` results in a concrete type such as `Array String`. You do this in type definitions (the _type langage_), not regular code (the _term language_). It's called a type constructor for the obvious reason that it constructs types.

**Comment by sporto** [comment]
Added mention to constructors in both union type and type alias sections
