### ISSUE TITLE
Tutorial code does not yet reflect a change to View.elm

### ISSUE THREAD

**Issue by BryanJBryce** [sporto/elm-tutorial#123]
Pull request #122 0.18 collapsed Html.App into Html so Html.App.map became Html.map.

This change is reflected in the code repo but not two places in the tutorial text for View.elm

```
page : Model -> Html Msg
page model =
    case model.route of
        PlayersRoute ->
            Html.App.map PlayersMsg (Players.List.view model.players)

        PlayerRoute id ->
            playerEditPage model id

        NotFoundRoute ->
            notFoundView
```

**Comment by sporto** [comment]
I made a global search and fixed several instances of `Html.App` still hanging around. Thanks for letting me know.
