### ISSUE TITLE
Suggestion : Update Player Commands example to use Json.Decode.Pipeline

### ISSUE THREAD

**Issue by kevohagan** [sporto/elm-tutorial#137]
Hi! I'm currently going through this tutorial! Thanks it's amazing! :) 
I would have a suggestion to update the players command section to use the Json.Decode.Pipeline library instead of Decode.map3. (http://package.elm-lang.org/packages/NoRedInk/elm-decode-pipeline/latest)

I also found the ``` import Json.Decode as Decode ``` a bit confusing in the type declarations afterwards e.g. ```Decode.Decoder (List Player)```

I find it more straightfowared to do something like ```import Json.Decode exposing (Decoder)``` and then ``` Decoder (List Player)```

I could submit a PR for these changes if you agree! 

Again thanks for the awesome tutorial!

**Comment by sporto** [comment]
Hi I agree about using `exposing (Decoder)` if that is the only thing being used in that module, I need to check that.

re. Pipeline. That package is great but I want to stick with core things at the moment unless the become really prevalent in the community. I will have a better look at it.

**Comment by sporto** [comment]
Latest version is using the decode pipeline.
