### ISSUE TITLE
Nit: misleading ` In package.json replace scripts with` in 04-starting/06-webpack-4

### ISSUE THREAD

**Issue by lucasdicioccio** [sporto/elm-tutorial#176]
Thanks for the amazing tutorial.

I've never used Yarn/WebPack before, hence I _guess_ it's a Yarn issue. The generated `package.json` does not contain a `scripts` key-value, hence the sentence should say something like "replace or add to the top-level JSON Object".

**Comment by sporto** [comment]
Fixed, thanks
