### ISSUE TITLE
Could not find command `package`

### ISSUE THREAD

**Issue by u0421793** [sporto/elm-tutorial#179]
On the first step of the first page in which I'm supposed to type stuff in from,
https://www.elm-tutorial.org/en/01-foundations/01-hello.html
the first thing I type fails:

`elm package install elm-lang/html`

This gives me this error message:

```
Could not find command `package`. Maybe there is a typo?

Default commands include:

  make      Compile an Elm file or project into JS or HTML
  package   Manage packages from <http://package.elm-lang.org>
  reactor   Develop with compile-on-refresh and time-travel debugging
  repl      A REPL for running individual expressions

When you try to run the command `package` we actually search for an
  executable named elm-package. Are you able to run elm-package?
  Is it on your PATH?
```
There is no explanation for what to do when I get such an error. Should I continue learning?

**Comment by caritos** [comment]
This worked for me:

elm-package install elm-lang/html
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 5.1.1
    elm-lang/html 2.0.0
    elm-lang/virtual-dom 2.0.4

Do you approve of this plan? [Y/n]

**Comment by u0421793** [comment]
That's interesting. You've typed a different line, not the one I was told to. Yes, it appears it now works with that unexpected and undocumented dash between `elm` and `package`. Thanks.

**Comment by sporto** [comment]
@u0421793 what OS are you using? You are not the first one that had trouble with `elm package`.

**Comment by u0421793** [comment]
linux

**Comment by sporto** [comment]
I have replaced `elm package` with `elm-package` as this have created issues a couple of times.
