### ISSUE TITLE
Update tutorial from to Elm 0.18 to 0.19

### ISSUE THREAD

**Issue by FranklinChen** [sporto/elm-tutorial#201]
Since Elm 0.19 changed many things https://github.com/elm/compiler/blob/master/upgrade-docs/0.19.md

**Comment by sporto** [comment]
Yes, this will happen thanks. I'm waiting for some feedback for the new version.

**Comment by sporto** [comment]
I have a version of the app for 0.19 https://github.com/sporto/elm-tutorial-app
It is more aligned to current community practices now.

But I have been busy with other stuff, will try to update the tutorial some time soon, but I don't have a timeframe.

**Comment by sporto** [comment]
I have decided to not work on this for the time being. So I don't think that a version 0.19 will happen. Thanks.
