### ISSUE TITLE
Tutorial maintenance + Translations to pt-br

### ISSUE THREAD

**Issue by dhelbegor** [sporto/elm-tutorial#202]
Hi, I'm was looking for a tutorial in the internet to learn elm, and i found this great tutorial, i'm very interested to collaborate for the translation of this to [pt-br], but firstly i need to know what is the future of this project

this project will be upgraded to the elm 0.19?

**Comment by FranklinChen** [comment]
https://github.com/sporto/elm-tutorial/issues/201

**Comment by sporto** [comment]
I'm would like to update this. I'm busy with other stuff, so I don't have a date to give.

**Comment by sporto** [comment]
I have tried, but couldn't find the time and energy to write the 0.19 version. I have decided to not work on this anymore for now. Thanks.
