### ISSUE TITLE
Elaboration on Mailboxes use of address

### ISSUE THREAD

**Issue by billc** [sporto/elm-tutorial#31]
I was following along on the Mailbox example and understand much of what is explained, except when you describe the final code sample. 

You did not get into much detail about the usage of `mb`. Specifically, I am confused on accessing `mb.address` and `mb.signal`. I am trying to break the mind frame of OOD, but this looks vaguely similar. 

Could you elaborate on the main and view section? It combines many different concepts into one quiet quickly.

Thanks for the tutorial. Very helpful so far.

**Comment by sporto** [comment]
I added a bit more explanation to these two sections. Trying to explain how `onClick` works is just too much at this point.

Also thought about adding a previous section using a mailbox directly, but I',m struggling to come up with a clean example.

**Comment by billc** [comment]
The added verbiage was very helpful! The Sequence Diagram is a good add as well, at least for me. Although, I did then question at what point is a Mailbox established. But, I plan to read ahead to understand associating multiple mailboxes.
