### ISSUE TITLE
More on Signal.forwardTo

### ISSUE THREAD

**Issue by andrewsuzuki** [sporto/elm-tutorial#34]
First of all, I'd just like to say that elm-tutorial is an absolutely amazing resource for learning Elm. Haven't found any other tutorials that come close to it!

On section 3.8 Composing, I think a little more should be added about Signal.forwardTo (there's currently only one sentence). Seems there have been a few of people confused about forwardTo so I think it should be expanded on. Max Goldstein says "You're not alone. Signal.forwardTo is, in my opinion, the hardest function to understand in the entire standard library".

https://groups.google.com/d/msg/elm-discuss/qCs0_7ZsIsE/0h8gR8vKDAAJ

https://www.reddit.com/r/elm/comments/3ntbiq/how_does_signalforwardto_work/

**Comment by sporto** [comment]
Thanks, I might wait until 0.17 is out to see what changes there are.

**Comment by sporto** [comment]
Not relevant anymore with 0.17
