### ISSUE TITLE
Section 11.5 - Can't compile when actions are not account for in Players Update

### ISSUE THREAD

**Issue by seadynamic8** [sporto/elm-tutorial#38]
Seciotn 11.5 - Can't compile when :
  | DeletePlayer PlayerId
  | DeletePlayerDone PlayerId (Result Http.Error ())
is not accounted for in the Players Update.

I just commented them out to get it to work, but maybe introduce them later when they are needed.

The tutorial is great and simple until it gets to Tasks and Effects, then it is way too complicated.  I had to spend sometime in other resources to get more up to speed on it.  But now I understand them enough to get through the tutorial.

I still don't have a handle on it without StartApp, loving those diagrams that show the flow though.
I'm going to go back and look at that scenario and see if I can figure it out.

If you could flesh out the beginner sections and maybe rearrange some of the explanations (since some of them happen after the first time we see it, by then I either got stuck or understood it already), it would be great!

Thanks for the tutorial!

**Comment by sporto** [comment]
Thanks for the opening this, I fixed the guide so it deals with the those unaccounted actions. I will try to make the chapter on effects simpler to understand, but I want to wait until Elm 0.17 is out to see what changes bring.
