### ISSUE TITLE
Elm-tutorial for offline reading

### ISSUE THREAD

**Issue by greyhwndz** [sporto/elm-tutorial#42]
It would be great and handy for elm-tutorial to be able to clone elm-tutorial and run locally for offline reading. Is this possible?

**Comment by rudolfb** [comment]
https://www.gitbook.com/book/sporto/elm-tutorial/details

You have links here to download PDF, MOBI or EPUB.

**Comment by sporto** [comment]
Added a link to that page in the tutorial home page. Thanks.

**Comment by rudolfb** [comment]
Thank _you_ for the super tutorial.

**Comment by greyhwndz** [comment]
Hey this is great! thanks thanks thanks! :+1:
