### ISSUE TITLE
Hop v4.0

### ISSUE THREAD

**Issue by mickeyvip** [sporto/elm-tutorial#48]
Hello and thank you so much for the tutorial!

Can you update the code to use Hop version `4` (I see the current version is `4.0.3`)?

I am trying to use it through the tutorial and since it requires to pass `Config` to `navigateTo`, I had moved the `routerConfig` into separate file along with `type Route` and `PathMatchers` declarations, so I would not have circular imports.

Thank you.

**Comment by sporto** [comment]
Yes, it is hard to use v4 with the current structure of the tutorial. I plan to fix this, but I'm considering waiting until Elm 0.17 is out (which seems around the corner), because there will be a new version of Hop and many changes to the tutorial.

**Comment by sporto** [comment]
Using the official Navigation lib in the lastest version.
