### ISSUE TITLE
Format all code examples with elm-format

### ISSUE THREAD

**Issue by romanzolotarev** [sporto/elm-tutorial#5]
Please allow me to format all code examples with https://github.com/avh4/elm-format.
Consistent styling may help beginners to learn Elm coding style as they go through this wonderful tutorial. @sporto What do you think?

Feel free to close this issue if you think code styling is fine as it is.

**Comment by romanzolotarev** [comment]
The current version or `elm-format` follows http://elm-lang.org/docs/style-guide:

## Example 1

``` diff
-type Action =
-  NoOp |
-  Refresh |
-  OnRefresh (Result Http.Error String)
+type Action
+  = NoOp
+  | Refresh
+  | OnRefresh (Result Http.Error String)
```

## Example 2

``` diff
view : Signal.Address Action -> Model -> Html.Html
view address message =  
-  Html.div [] [
-    Html.button [
-      Events.onClick address Refresh
-    ]
-    [
-      Html.text "Refresh"
-    ],
-    Html.text message
-  ]
+  Html.div
+    []
+    [ Html.button
+        [ Events.onClick address Refresh ]
+        [ Html.text "Refresh" ]
+    , Html.text message
+    ]
```

**Comment by sporto** [comment]
@romanzolotarev     ok, I agree that consistent code styles trumps my personal preference, I will do it using the elm-format cli as I have all the examples in a repository

**Comment by romanzolotarev** [comment]
@sporto Created PR #6. Could you please review it?
Closing this issue as a duplicate.
