### ISSUE TITLE
List of Maybe, not

### ISSUE THREAD

**Issue by janne** [sporto/elm-tutorial#69]
I don't agree that using a List over Maybe is a good idea. A better approach is to use `Maybe.map`, like:

Like so:

``` elm
import Html exposing (..)

findItem id items =
    List.filter (\item -> item.id == id) items
        |> List.head

main =
  Maybe.map .id (findItem 2 [{id = 1}, {id = 2}])
    |> toString
    |> text
```

**Comment by janne** [comment]
You can even chain them like:

``` elm
(findItem 2 [{id = 1}, {id = 2}]) |> Maybe.map .id |> Maybe.map ((*) 2)
```

**Comment by sporto** [comment]
Ok, you are the second person telling me that `Maybe.map` could be better. I think I'll remove this section.

**Comment by sporto** [comment]
Done, removed as this seems to be a best practice after all.

**Comment by janne** [comment]
Cool, thanks.

2016-06-30 0:28 GMT+02:00 Sebastian Porto notifications@github.com:
