### ISSUE TITLE
how to pass Message from child module to parent module in Elm architecture?

### ISSUE THREAD

**Issue by romdarom** [sporto/elm-tutorial#75]
Hi folks, i don't know whether it's the right place, but i'll take the chance because you talk about the Elm Architecture.
So, it's all in the title. To illustrate my case, i'll use a case study.
Imagine you've got a child module whose UI is a text input, enriched with various things. As I enter text its model is updated. This child's model is held into the parent model. 
you might tell me that from the parent's perspective, you just have to listen to the child's model and get anything you need out. Ok, but now, let's say you want a "enter" key stroke to notify that this word must be "sent" to its parent ... ok, you might suggest adding a bool knowing when i can use the proper input from the parent's perspective... 
But now, the concept of Message (passing) is being replaced by data  + bools ... not good at all. 
So, here is the question : **how to pass message from Child module to Parent module**? 
does the Elm architecture fit that way of building softwares ? 

Thanks for your answer

**Comment by sporto** [comment]
Hi, there is a lot of discussion about this going on in the community lately.
Please see these three blog post:

http://folkertdev.nl/blog/elm-child-parent-communication

https://medium.com/@alex.lew/the-translator-pattern-a-model-for-child-to-parent-communication-in-elm-f4bfaa1d3f98#.7a2suqbxk

https://www.brianthicks.com/post/2016/06/23/candy-and-allowances-parent-child-communication-in-elm/

I think that from them you will be able to find the best approach that works for you. Thanks.

**Comment by romdarom** [comment]
Hi. Thank you so much for your response. I took the time to thoroughly read all those articles before responding. Very good read. These articles will surely help me build composable components.

**Comment by sporto** [comment]
I will close this now, as there doesn't seem to be any further action required
