### ISSUE TITLE
Missing package install instructions

### ISSUE THREAD

**Issue by nikcorg** [sporto/elm-tutorial#8]
After spending last night reading through the tutorial and playing with the [online editor](http://elm-lang.org/try), I finally took the plunge and installed `elm-platform` and started playing around. I was pretty stumped when my `Hello.elm` crashed with a missing package error.

The Hello world example mentions the [`Html` module being a part of core](https://github.com/sporto/elm-tutorial/blame/master/foundations/hello.md#L38), which doesn't seem to be the case. Rather it is a separate [package](http://package.elm-lang.org/packages/evancz/elm-html/4.0.2/) that needs to be installed using `elm-package`.

(The assets repo has an `elm-package.json` with [a few deps listed](https://github.com/sporto/elm-tutorial-assets/blob/master/elm-package.json#L11-L15), including `elm-html`.)

Did I make a mistake or is indeed the mishap in the tutorial? I'll be happy to send a patch to the Hello world -and other parts- as I garner valuable experience going through while actually doing the exercises, as long as it's not just another PEBKAC.

**Comment by nikcorg** [comment]
Looking around docs, perhaps you initially intended to use the `Graphics.Element` package, which apparently is in core, but you later changed your mind?

**Comment by sporto** [comment]
You are right, not part of core, will fix this thanks

**Comment by nikcorg** [comment]
@sporto I'm happy to send a PR, if you llke. I just wanted to confirm it wasn't a blunder on my part.

**Comment by sporto** [comment]
Done, thanks
