### ISSUE TITLE
The font in .pdf version

### ISSUE THREAD

**Issue by FoggyFinder** [sporto/elm-tutorial#83]
Can you increase the font size in the .pdf version? Now it's too small, uncomfortable to read.

![1](https://cloud.githubusercontent.com/assets/16510738/17492092/5688d91e-5dbb-11e6-8d43-91f722edcc57.jpg)

**Comment by sporto** [comment]
No, sorry, it is all done by the gitbook platform, I suggest zooming the pdf when reading.

**Comment by FoggyFinder** [comment]
It's strange -  all the other gitbook that I've read had larger font size.
In any case, if the cause is in the platform, it only remains for me to close the issue.
