### ISSUE TITLE
hello world compiles with warning

### ISSUE THREAD

**Issue by dexter1100** [sporto/elm-tutorial#84]
With Elm 0.17.1 on Windows 10 using Brackets the hello world program in the tutorial compiles with the warning:

`missing type annotation
Top-level value 'main' does not have a type annotation.
I inferred the type annotation so you can copy it into your code:

main: Html.Html a

Successfully generated index.html`

It's just a warning though. The message "Hello" can be seen in the browser.

**Comment by sporto** [comment]
Yes, true. I avoided putting the type annotation at this stage to keep it simple. I will put a note on this.
