### ISSUE TITLE
no explanation for module Hello exposing (..)

### ISSUE THREAD

**Issue by dexter1100** [sporto/elm-tutorial#85]
As the title says there's no explanation for what `module Hello exposing (..)` does in the [hello world tutorial](http://www.elm-tutorial.org/en/01-foundations/01-hello.html). That line is also missing from the [hello world example page](http://elm-lang.org/examples/hello-html).

**Comment by sporto** [comment]
Fixed in the tutorial. That example in http://elm-lang.org/examples/hello-html is adding the module declaration behind the scenes.
