### ISSUE TITLE
Missing syntax highlighting

### ISSUE THREAD

**Issue by davegomez** [sporto/elm-tutorial#88]
I have notice that some code blocks doesn't have the syntax highlighting feature, is this intentional or do you think it should be resolve?

Example: [05-union-types.md](https://github.com/sporto/elm-tutorial/blob/master/en/01-foundations/05-union-types.md)

I can help you with that if you want me to.

**Comment by sporto** [comment]
This is an omission on my part, very happy to get some help to fix this.
